# Generated by Django 5.1.2 on 2024-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('primera_vez', models.BooleanField()),
                ('numero_comensales', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
